# MLE 24/25 - Coursework 1

## Guidelines

### Setting up the coursework

To start, download the file `cw2.zip` from the module’s Keats website. Once this is done:
- Unzip the file `cw2.zip` in a folder of your choice. We will refer to this folder as `<FOLDER>`.
- Make a duplicate of the Notebook file `<FOLDER>/coursework.ipynb` and rename it to `<FOLDER>/<K_NUM>.ipynb`. For instance, if your k number is "k12345678", your coursework file will be located at `<FOLDER>/k12345678.ipynb`.
- Open Anaconda, select the environment "ml4eng", and launch Jupyter Lab. Open your coursework file `<FOLDER>/<K_NUM>.ipynb`.
 
### Instructions

In this coursework, you will complete a series of functions that will be called in the following cells.
Each question will specify which function should be completed, as well as its expected behaviour.
**You must ONLY modify the code inside the mentioned functions at each question. Most importantly, you must NOT edit the name of the provided functions, or the order/name of its input parameters.**
**If you do, we will be unable to mark your project.**
We will also specify the format of the inputs and the required format of the outputs in the function description.

For instance, let's assume we have a question that asks us to complete function named `example`, which sums the entries of a vector `v` given as input.
The function to complete will be presented as follows:

In [1]:
def example(v):
    """
    Parameters
    ----------
    v : np.ndarray
        N x 1 numpy array with `float` elements
    
    Returns
    -------
    sum_v : float
        Sum of elements in v
    """
    
    # Write your code here


_Note: we use `np.ndarray` to indicate the corresponding variable is a NumPy array._

**Functions that do not respect the specified output format or order will not be awarded any point.**\
**Additionally, your function must only rely on the given inputs or the variables created within the function itself, and not use any variable created inside the Notebook instance.**\
Nonetheless, you are allowed to re-use functions implemented in previous questions.

Please avoid defining two functions with the same name, write your code directly inside the available function template, i.e., just below the comment `# Write your code here`.

Once a function has been completed, it will be usually called in the following cells, and you will be able to check that it provides the intended results.
If you want to inspect your function in more detail, we recommend that you do so in a separate Notebook (e.g., by duplicating the present Notebook) and keep the file `<K_NUM>.ipynb` for your final implementation.

Please avoid submitting functions that display text in your final submission.
You are free (and encouraged) to add `print` statements while completing the functions, but do not forget to remove them in the final submission.

You are only allowed to use the libraries loaded in the section "Import libraries", that is: `numpy`, `scipy.stats` and `matplotlib.pyplot`.


### Submitting your coursework

Before submitting your work, you must re-run your completed Notebook with a clean Notebook instance in order to ensure that there are no variables defined in your instance that are causing side-effects.
For this, follow the instructions below:
- Restart your kernel and clear your outputs (in the menu bar of Jupyter Lab: `Kernel > Restart Kernel and Clear Outputs of All Cells...`): this will remove all pre-existing variables and outputs of your code cells.
- Re-run all cells of your notebook in order (_hint: you can use `shift+enter` to run a cell and select the next cell_)

Please make sure that all functions output the right dimensions, as specified in the corresponding question, and that no function raises an error.
**No points will be awarded for functions that do not output the right dimensions, or to functions that raise an error.**

Finally, compress your Notebook file `<K_NUM>.ipynb` into a zip file with name `<K_NUM>.zip` and submit it to KEATS.
**Please ensure your `.zip` file ONLY contains the notebook you wish to submit. You do not have to include the dataset in your `.zip` file and you MUST NOT submit multiple Notebooks, only include the one you wish to be marked.**

**Again, please ensure all cells of the submitted Notebook are executed, even if the corresponding cell results in an error.**

## Introduction

In this coursework, we will work with a modified version of the _Diabetes Dataset_ from the National Institute of Diabetes and Digestive and Kidney Diseases.
This dataset includes $N^\mathrm{all} = 768$ entries, each representing $K = 7$ clinical features of a given patient plus a binary target variable, which indicates whether or not the patient developed diabetes.
The goal of this coursework will be to learn a predictor that quantifies the likelihood of a partient developping diabetes based on their clinical features.

A description of the features and target variables is available in the table below, along with the column index of each variable.


| Name                       | Column Index | Feature/Target | Max Value | Description                                                                                                                              |
|----------------------------|--------------| -------------- | --------- | ---------------------------------------------------------------------------------------------------------------------------------------- |
| Age                        | 0            | Feature        | 81        | The age of the patient in years.                                                                                                         |
| BloodPressure              | 1            | Feature        | 122       | The diastolic blood pressure ($\text{mm} \cdot \text{Hg}$) of the patient.                                                               |
| BMI                        | 2            | Feature        | 67.1      | Body Mass Index, calculated as weight in $\text{kg} \cdot \text{m}^{-2}$.                                                                |
| Diabetes Pedigree Function | 3            | Feature        | 2.42      | A function that scores the likelihood of diabetes based on family history. Higher values indicate a stronger family history of diabetes. |
| Glucose                    | 4            | Feature        | 199       | The plasma glucose concentration measured after a 2-hour oral glucose tolerance test ($\text{mg} \cdot \text{dL}^{-1}$).                 |
| Insulin                    | 5            | Feature        | 846       | The 2-hour serum insulin level ($\mu \text{U} \cdot \text{ml}^{-1}$).                                                                    |
| Skin Thickness             | 6            | Feature        | 99        | The triceps skin fold thickness ($\text{mm}$), which is a measure of body fat.                                                           |
| Has Diabetes               | 7            | Target         | -         | Label equal to `1` if the patient has diabetes, and `0` if he/she does not.                                                              |


The values of the features in the dataset have been normalized by their respective maximum value.
Accordingly, all the values are in the range $[0, 1]$, where $1$ indicates that the feature is equal to its maximum value.

We will denote the available dataset as $\mathcal{D}^\mathrm{all} = {(x_i, t_i)}_{i=0}^{N^\mathrm{all}-1}$, where $N = 768$ is the number of available datapoints, $x_i \in \mathbb{R}^K$ is a $K \times 1$ vector containing the $K = 7$ normalized feature values of the $i$-th datapoint (column indices from `0` to `6` in the table above), and $t_i \in \{0, 1\}$ is its associated label (column index `7` above).
We will use the notation
\begin{equation*}
X_{\mathcal{D}^\mathrm{all}} = \begin{bmatrix}
(x_0)^\top \\
\vdots \\
(x_{N^\mathrm{all}-1})^\top
\end{bmatrix}
\end{equation*}
to denote the $N^\mathrm{all} \times K$ data matrix associated to the dataset $\mathcal{D}^\mathrm{all}$, and we will use
\begin{equation*}
t_{\mathcal{D}^\mathrm{all}} = \begin{bmatrix}
t_0 \\
\vdots \\
t_{N^\mathrm{all}-1}
\end{bmatrix}
\end{equation*}
to denote the associated $N \times 1$ targets vector.

Throughout this coursework, we will use $\mathcal{D} \subset \mathcal{D}^\mathrm{all}$ to denote an arbitrary dataset subset of size $N \leq N^\mathrm{all}$. 
For simplicity, we will assume the elements of $\mathcal{D} = {(x_i, t_i)}_{i=0}^{N-1}$ to be indexed from $0$ to $N-1$.
In a similar fashion as above, we also define its associated $N \times K$ data matrix $X_{\mathcal{D}}$ and $N \times 1$ target vector $t_{\mathcal{D}}$.

This coursework is split into two parts:
- In the first part, we will train and evaluate a logistic regression algorithm.
- In the second part, we will train and evaluate a neural network via backpropagation.


## Import libraries

In [2]:
import numpy as np
import scipy.stats as st
import matplotlib.pyplot as plt

## Load dataset

Loads the _Diabetes Dataset_ and splits it into $N^\mathrm{tr} = 668$ training samples $\mathcal{D}^{\mathrm{tr}} = {(x_i, t_i)}_{i=0}^{N^\mathrm{tr} - 1}$ and $N^\mathrm{te} = N^\mathrm{all} - N^\mathrm{tr} = 100$ test samples $\mathcal{D}^\mathrm{te} = {(x_i, t_i)}_{i=N^\mathrm{tr}}^{N-1}$.


In [3]:
# Load dataset and split into test and training
dataset_tr_te = np.load("dataset.npy")
dataset_tr = dataset_tr_te[:668, :]  # Training dataset
dataset_te = dataset_tr_te[668:, :]  # Test dataset

# Split dataset into inputs (covariates) and targets (labels)
n_dataset_features = 7  # Number of covariate features in the dataset
dataset_inputs_tr = dataset_tr[:, :n_dataset_features]  # Training data matrix
dataset_targets_tr = dataset_tr[:, n_dataset_features].reshape(-1, 1)  # Training targets vector
dataset_inputs_te = dataset_te[:, :n_dataset_features]  # Test data matrix
dataset_targets_te = dataset_te[:, n_dataset_features].reshape(-1, 1)  # Test targets vector

## Part I

In this first section, we will implement a logistic regression classifier.
Accordingly, we will denote as $\theta$ its $K \times 1$ parameter vector, and a soft prediction will be given as $p(\mathrm{t}_i = 1 | x_i, \theta) = \sigma(\theta^\top x_i)$, where
\begin{equation*}
    \sigma(x) = \frac{1}{1 + \exp(-x)}
\end{equation*}
represents the sigmoid function applied to a real number $x \in \mathbb{R}$.

### Question 1 [5 points]

Complete the function `sigmoid` which takes as input a matrix 
\begin{equation*}
U = \begin{bmatrix}
u_{0, 0} & \dots & u_{0, N_2 - 1} \\
\vdots & \ddots & \vdots \\
u_{N_1 - 1, 0} & \dots & u_{N_1 - 1, N_2 - 1}
\end{bmatrix}
\end{equation*}
of any shape $N_1 \times N_2$, and returns a matrix of the same shape
\begin{equation*}
\sigma(U) = \begin{bmatrix}
\sigma(u_{0, 0}) & \dots & \sigma(u_{0, N_2 - 1}) \\
\vdots & \ddots & \vdots \\
\sigma(u_{N_1 - 1, 0}) & \dots & \sigma(u_{N_1 - 1, N_2 - 1})
\end{bmatrix}
\end{equation*}
corresponding to the element-wise application of the sigmoid function to the coefficients of $U$.

In [4]:
def sigmoid(mat):
    """
    Parameters
    ----------
    mat : np.ndarray
        Matrix of arbitrary shape N_1 x N_2
    
    Returns
    -------
    sigma_mat : np.ndarray
        Matrix of shape N_1 x N_2 corresponding to the application of sigmoid function to the coefficients of `mat`.
    """

    # Write your code here

    sigma_mat = 1 / (1 + np.exp(-mat))
    
    return sigma_mat

In [5]:
U = np.linspace(-3, 3, 30).reshape(5, 6)
sigmoid_U = sigmoid(U)

print(f"Dummy matrix 'U':\n{U}\n")
print(f"Sigmoid values 'sigma(U)':\n{sigmoid_U}")

Dummy matrix 'U':
[[-3.         -2.79310345 -2.5862069  -2.37931034 -2.17241379 -1.96551724]
 [-1.75862069 -1.55172414 -1.34482759 -1.13793103 -0.93103448 -0.72413793]
 [-0.51724138 -0.31034483 -0.10344828  0.10344828  0.31034483  0.51724138]
 [ 0.72413793  0.93103448  1.13793103  1.34482759  1.55172414  1.75862069]
 [ 1.96551724  2.17241379  2.37931034  2.5862069   2.79310345  3.        ]]

Sigmoid values 'sigma(U)':
[[0.04742587 0.05769799 0.07003141 0.08476405 0.10225524 0.12287119]
 [0.14696317 0.17483739 0.20671728 0.24270043 0.28271489 0.32648243]
 [0.37349752 0.42303057 0.47416097 0.52583903 0.57696943 0.62650248]
 [0.67351757 0.71728511 0.75729957 0.79328272 0.82516261 0.85303683]
 [0.87712881 0.89774476 0.91523595 0.92996859 0.94230201 0.95257413]]


### Question 2 [10 points]

Complete the function `logistic_regression_prediction` which takes as input a data matrix $X_{\mathcal{D}}$ and a parameter vector $\theta$, and returns the $N \times 1$ vector of element-wise soft predictions $\hat{p} = [p(\mathrm{t}_0 = 1 | x_0, \theta), ..., p(\mathrm{t}_{N-1} = 1 | x_{N-1}, \theta)]^\top$.

In [6]:
def logistic_regression_prediction(inputs, theta):
    """
    Parameters
    ----------
    inputs : np.ndarray
        N x K data matrix
    
    theta : np.ndarray
        K x 1 parameter vector
    
    Returns
    -------
    p_hat : np.ndarray
        N x 1 vector of element-wise soft predictions
    """

    # Write your code here

    # Compute logits for all data samples
    logit = inputs @ theta 

    # Use sigmoid function to logits to get probabilities
    p_hat = sigmoid(logit)

    
    return p_hat
        
        
    

In [7]:
dummy_theta = np.array([1.0, -1.0, 1.0, -1.0, -1.0, 1.0, -1.0]).reshape(-1, 1)
dummy_logistic_reg_preds = logistic_regression_prediction(np.copy(dataset_inputs_tr), dummy_theta)

print("First 5 rows of training inputs matrix:")
print(dataset_inputs_tr[:5, :])
print("First 5 rows of training soft predictions (dummy parameters):")
print(dummy_logistic_reg_preds[:5, :])

First 5 rows of training inputs matrix:
[[0.37  0.508 0.443 0.157 0.588 0.    0.121]
 [0.321 0.459 0.31  0.14  0.482 0.058 0.172]
 [0.42  0.525 0.455 0.579 0.533 0.141 0.354]
 [0.568 0.623 0.675 0.08  0.337 0.    0.   ]
 [0.296 0.492 0.529 0.171 0.543 0.21  0.465]]
First 5 rows of training soft predictions (dummy parameters):
[[0.36331611]
 [0.36262244]
 [0.27388502]
 [0.55057644]
 [0.3461513 ]]


### Question 3 [5 points]

Complete the function `cross_entropy_loss` which takes as input the soft predictions $\hat{p} = [p(\mathrm{t}_0 = 1 | x_0, \theta), ..., p(\mathrm{t}_{N-1} = 1 | x_{N-1}, \theta)]^\top$ and the corresponding target vector $t_{\mathcal{D}}$; and returns the cross-entropy loss
\begin{equation*}
    \mathcal{L}_{\mathcal{D}}(\theta) = \frac{1}{N} \sum_{i=0}^{N-1} \ell_i(\theta),
\end{equation*}
under the parameters $\theta$ on dataset $\mathcal{D}$, where
\begin{equation*}
\begin{split}
\ell_i(\theta) &=  -\log\left( p(\mathrm{t}_i = t_i | x_i, \theta) \right) \\
    &= -t_i \log\left( p(\mathrm{t}_i = 1 | x_i, \theta) \right) - (1 - t_i) \log\left( 1 - p(\mathrm{t}_i = 1 | x_i, \theta) \right),
\end{split}
\end{equation*}
is the log-loss of the $i$-th datapoint.

In [8]:
def cross_entropy_loss(soft_predictions, targets):
    """
    Parameters
    ----------
    soft_predictions : np.ndarray
        N x 1 vector of element-wise soft predictions
    
    targets : np.ndarray
        N x 1 target vector
    
    Returns
    -------
    loss : float
        Scalar cross-entropy loss
    """

    # Write your code here

    # Compute element-wise loss, and mean to find average loss
    
    log_loss = - np.mean(
        targets * np.log(soft_predictions) + (1 - targets) * np.log(1 - soft_predictions)
    )
    return log_loss



In [9]:
dummy_targets = np.array([1., 0., 0., 1., 0.]).reshape(-1, 1)
dummy_soft_preds = np.array([0.9, 0.5, 0.1, 0.3, 0.7]).reshape(-1, 1)
dummy_loss = cross_entropy_loss(dummy_soft_preds, dummy_targets)

print("Dummy targets:")
print(dummy_targets)
print("Dummy soft predictions")
print(dummy_soft_preds)
print(f"Empirical cross-entropy loss: {dummy_loss}")

Dummy targets:
[[1.]
 [0.]
 [0.]
 [1.]
 [0.]]
Dummy soft predictions
[[0.9]
 [0.5]
 [0.1]
 [0.3]
 [0.7]]
Empirical cross-entropy loss: 0.662362764105494


### Question 4 [10 points]

Complete the function `logistic_regression_gradient` which takes as input a data matrix $X_{\mathcal{D}}$, its corresponding target vector $t_\mathcal{D}$, and the soft predictions $\hat{p} = [p(\mathrm{t}_0 = 1 | x_0, \theta), ..., p(\mathrm{t}_{N-1} = 1 | x_{N-1}, \theta)]^\top$; and returns the gradient of the loss with respect to the parameters $\theta$ as
\begin{equation*}
    \nabla \mathcal{L}_{\mathcal{D}}(\theta) = \frac{1}{N} \sum_{i=0}^{N-1} \nabla \ell_i(\theta),
\end{equation*}
where $\nabla \mathcal{L}_{\mathcal{D}}(\theta)$ denotes the $K \times 1$ gradient of $\mathcal{L}_{\mathcal{D}}(\theta)$ with respect to the parameter vector $\theta$.
The gradient must be computed using **symbolic differentiation** (and **not** using numerical differentiation).
The gradient is assumed to be evaluated at the same parameter vector $\theta$ used to generate the soft prediction $\hat{p}$.

In [10]:
def logistic_regression_gradient(inputs, targets, soft_predictions):
    """
    Parameters
    ----------
    inputs : np.ndarray
        N x K data matrix
    
    targets : np.ndarray
        N x 1 target vector
    
    soft_predictions : np.ndarray
        N x 1 vector of element-wise soft predictions
    
    Returns
    -------
    gradient : np.ndarray
        K x 1 gradient vector
    """

    # Compute mean error
    mean_error = soft_predictions - targets

    # Compute gradient using matrix multiplication
    gradient = (inputs.T @ mean_error) / len(targets)
        
    return gradient

In [11]:
# Create a dummy dataset consisting of 10 datapoints
dummy_inputs = np.array([
    [0.275, 0.239, 0.258, 0.   , 0.   ],
    [0.31 , 0.325, 0.223, 0.   , 0.24 ],
    [0.37 , 0.324, 1.191, 0.   , 0.   ],
    [0.36 , 0.385, 0.821, 0.082, 0.3  ],
    [0.41 , 0.519, 0.27 , 0.272, 0.39 ],
    [0.4  , 0.536, 0.693, 0.   , 0.   ],
    [0.42 , 0.449, 0.586, 0.192, 0.21 ],
    [0.39 , 0.345, 0.258, 0.   , 0.3  ],
    [0.4  , 0.43 , 0.402, 0.   , 0.   ],
    [0.39 , 0.37 , 0.439, 0.022, 0.27 ]
])
dummy_targets = np.array([0., 0., 1., 0., 0., 1., 1., 0., 1., 0.]).reshape(-1, 1)
dummy_logistic_reg_soft_preds = np.array([0.1, 0.4, 0.6, 0.6, 0.8, 0.2, 0.1, 0.3, 0.15, 0.9]).reshape(-1, 1)

# Evaluate logistic gradient function
dummy_gradient = logistic_regression_gradient(dummy_inputs, dummy_targets, dummy_logistic_reg_soft_preds)
print(f"Logistic regression gradient (dummy data):\n{dummy_gradient}")

Logistic regression gradient (dummy data):
[[-0.00225]
 [-0.00914]
 [-0.06038]
 [ 0.01138]
 [ 0.0732 ]]


### Question 5 [10 points]

Complete the function `gradient_descent_step` which takes as input the gradient $\nabla \mathcal{L}_{\mathcal{D}}(\theta^{(l)})$ evaluated at the current parameter iterate $\theta^{(l)}$ (also given as input) and a learning rate $\gamma > 0$; and outputs the next parameter iterate $\theta^{(i+1)}$ by applying the gradient descent step
\begin{equation*}
    \theta^{(l+1)} = \theta^{(l)} - \gamma \nabla \mathcal{L}_{\mathcal{D}}(\theta^{(l)}).
\end{equation*}

In [12]:
def gradient_descent_step(theta, gradient, lr):
    """
    Parameters
    ----------
    theta : np.ndarray
        K x 1 parameter vector
    
    gradient : np.ndarray
        K x 1 gradient vector
    
    lr : float
        Scalar learning rate
    
    Returns
    -------
    new_theta : np.ndarray
        K x 1 parameter vector after gradient-descent update
    """

    # Write your code here
    new_theta = theta - lr*gradient
    
    return new_theta

In [13]:
# Dummy inputs
n_dummy_features = 7
dummy_theta = np.zeros(n_dummy_features, dtype=float).reshape(-1, 1)
dummy_gradient = np.arange(n_dummy_features, dtype=float).reshape(-1, 1)
dummy_lr = 0.1

# Gradient descent step
new_theta = gradient_descent_step(dummy_theta, dummy_gradient, dummy_lr)

print(f"Initial dummy parameter:\n{dummy_theta}")
print(f"Dummy gradient:\n{dummy_gradient}")
print(f"Learning rate:{dummy_lr}")
print(f"New parameter after gradient descent step:\n{new_theta}")

Initial dummy parameter:
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]
Dummy gradient:
[[0.]
 [1.]
 [2.]
 [3.]
 [4.]
 [5.]
 [6.]]
Learning rate:0.1
New parameter after gradient descent step:
[[ 0. ]
 [-0.1]
 [-0.2]
 [-0.3]
 [-0.4]
 [-0.5]
 [-0.6]]


### Question 6 [10 points total]

#### Question 6.1 [5 points]

Complete the function `train_logistic_regression` which takes as input
- the data matrix $X_\mathcal{D}$,
- its associated target vector $t_\mathcal{D}$,
- an initial value $\theta^{(0)}$ of the parameter vector, 
- a learning rate $\gamma > 0$
- a number of gradient-descent steps $L$;

and returns the learned parameter $\theta^{(L)}$ after $L$ gradient-descent steps on the dataset $\mathcal{D}$.

In [14]:
def train_logistic_regression(inputs, targets, init_theta, lr, n_gd_steps):
    """
    Parameters
    ----------
    inputs : np.ndarray
        N x K data matrix
    
    targets : np.ndarray
        N x 1 target vector
        
    init_theta : np.ndarray
        K x 1 parameter vector initial value
    
    lr : float
        Scalar learning rate
    
    n_gd_steps : int
        Number of gradient-descent steps
    
    Returns
    -------
    learned_theta : np.ndarray
        K x 1 parameter vector learned after `n_gd_steps` gradient-descent steps
    """

    learned_theta = init_theta
    # Write your code here
    for i in range(n_gd_steps):
        
        soft_predictions = sigmoid(np.matmul(inputs, learned_theta)) # Using the sigmoid function defined earlier, 
        # we can calculate a vector of predictions via matrix multiplication of theta and x
        gradient = logistic_regression_gradient(inputs, targets, soft_predictions) # Then use function logistic_gradeint_descent for gradient 
        learned_theta = gradient_descent_step(learned_theta, gradient, lr) # and use gradient_descent_step for one step

    
    return learned_theta

In [15]:
# Create a dummy dataset consisting of 10 datapoints
dummy_inputs = np.array([
    [0.233, 0.275, 0.239, 0.258, 0.4  , 0.   , 0.   ],
    [0.278, 0.31 , 0.325, 0.223, 0.54 , 0.   , 0.24 ],
    [0.433, 0.37 , 0.324, 1.191, 0.985, 0.   , 0.   ],
    [0.267, 0.36 , 0.385, 0.821, 0.535, 0.082, 0.3  ],
    [0.3  , 0.41 , 0.519, 0.27 , 0.76 , 0.272, 0.39 ],
    [0.233, 0.4  , 0.536, 0.693, 0.59 , 0.   , 0.   ],
    [0.567, 0.42 , 0.449, 0.586, 0.905, 0.192, 0.21 ],
    [0.411, 0.39 , 0.345, 0.258, 0.44 , 0.   , 0.3  ],
    [0.489, 0.4  , 0.43 , 0.402, 0.66 , 0.   , 0.   ],
    [0.444, 0.39 , 0.37 , 0.439, 0.63 , 0.022, 0.27 ]
])
dummy_targets = np.array([0., 0., 1., 0., 0., 1., 1., 0., 1., 0.]).reshape(-1, 1)

# Init model parameters
n_dummy_features = 7
dummy_init_theta = np.ones(n_dummy_features, dtype=float).reshape(-1, 1)

# Training parameters
dummy_n_gd_steps = 100
dummy_lr = 0.1

# Evaluate function
dummy_learned_theta = train_logistic_regression(dummy_inputs, dummy_targets, dummy_init_theta, dummy_lr, dummy_n_gd_steps)

print(f"Learned parameter on dummy samples:\n{dummy_learned_theta}")


Learned parameter on dummy samples:
[[ 0.19873971]
 [ 0.02518555]
 [ 0.03270425]
 [ 0.28887299]
 [-0.32684191]
 [ 0.78003004]
 [ 0.01735104]]


### Question 6.2 [5 points]

Complete the function `train_and_test_logistic_regression` which takes as input
- the training data matrix $X_{\mathcal{D}^\mathrm{tr}}$,
- the training target vector $t_{\mathcal{D}^\mathrm{tr}}$,
- the test data matrix $X_{\mathcal{D}^\mathrm{te}}$,
- the test target vector $t_{\mathcal{D}^\mathrm{te}}$,
- an initial value $\theta^{(0)}$ of the parameter vector, 
- a learning rate $\gamma > 0$
- a number of gradient-descent steps $L$;

and returns
- the learned parameter $\theta^{(L)}$ after $L$ gradient-descent steps on the dataset $\mathcal{D}$,
- the training loss $\mathcal{L}_{\mathcal{D}^\mathrm{tr}}(\theta^{(L)})$,
- and the test loss $\mathcal{L}_{\mathcal{D}^\mathrm{te}}(\theta^{(L)})$.

In [16]:
def train_and_test_logistic_regression(inputs_tr, targets_tr, inputs_te, targets_te, init_theta, lr, n_gd_steps):
    """
    Parameters
    ----------
    inputs_tr : np.ndarray
        N_tr x K training data matrix
    
    targets_tr : np.ndarray
        N_tr x 1 training target vector

    inputs_te : np.ndarray
        N_te x K test data matrix
    
    targets_te : np.ndarray
        N_te x 1 test target vector
        
    init_theta : np.ndarray
        K x 1 parameter vector initial value
    
    lr : float
        Scalar learning rate
    
    n_gd_steps : int
        Number of gradient-descent steps
    
    Returns
    -------
    learned_theta : np.ndarray
        K x 1 parameter vector learned after `n_gd_steps` gradient-descent steps

    loss_tr : float
        Scalar cross-entropy training loss

    loss_te : float
        Scalar cross-entropy test loss
    """

    # Write your code here
    
    # Use train_logistic_regressions to calculate learned_theta
    learned_theta = train_logistic_regression(inputs_tr, targets_tr, init_theta, lr, n_gd_steps) 

    # Use matmul and sigmoid to calculate soft_predictions_tr and soft_predictions_te
    soft_predictions_tr = sigmoid(np.matmul(inputs_tr, learned_theta))
    
    soft_predictions_te = sigmoid(np.matmul(inputs_te, learned_theta))

    # Then use cross_entropy_loss to compute loss_tr and loss_te
    loss_tr = cross_entropy_loss(soft_predictions_tr, targets_tr)
    
    loss_te = cross_entropy_loss(soft_predictions_te, targets_te)

    return learned_theta, loss_tr, loss_te

In [17]:
# Init model parameters
n_dataset_features = 7
dataset_init_theta = np.ones(n_dataset_features, dtype=float).reshape(-1, 1)

# Init learning parameters
dataset_n_gd_steps = 20000
dataset_lr = 0.05


# Train logistic regression and estimate the population loss for the learned parameter
dataset_learned_theta, dataset_loss_tr, dataset_loss_te = train_and_test_logistic_regression(
    np.copy(dataset_inputs_tr),
    np.copy(dataset_targets_tr),
    np.copy(dataset_inputs_te),
    np.copy(dataset_targets_te),
    dataset_init_theta,
    dataset_lr,
    dataset_n_gd_steps
)


print(f"Learned parameter 'theta' (diabetes dataset):\n{dataset_learned_theta}")
print(f"Train loss (diabetes dataset): {dataset_loss_tr}")
print(f"Estimated population loss for learned parameter (diabetes dataset): {dataset_loss_te}")

Learned parameter 'theta' (diabetes dataset):
[[ 0.69027026]
 [-3.76899381]
 [-0.50650655]
 [ 0.54826923]
 [ 2.36417276]
 [ 0.65256661]
 [ 0.02322827]]
Train loss (diabetes dataset): 0.6164908278244284
Estimated population loss for learned parameter (diabetes dataset): 0.6620104796260169


## Part II

In this second section, we will implement a neural network with a single feature extraction layer of $M = 10$ neurons using a ReLu activation function 
\begin{equation*}
    h(a) = \max(a, 0).
\end{equation*}
Accordingly, the parameters to be learned are $\theta = \{W^\mathrm{feat}, W^\mathrm{class}\}$, where $W^\mathrm{feat}$ denotes the $M \times K$ matrix of weights for the feature extraction layer, and $W^\mathrm{class}$ denotes the $1 \times M$ matrix of weights for the classification layer.
For a given $K \times 1$ covariate vector $x_i$, the neural network computes a soft prediction as follows:
\begin{equation*}
\begin{split}
    &a^\mathrm{feat} = W^\mathrm{feat} x_i \\
    &h^\mathrm{feat} = h(a^\mathrm{feat}) \\
    &a^\mathrm{class} = W^\mathrm{class} h^\mathrm{feat} \\
    &p(\mathrm{t}_i = 1 | x_i, \theta) = \sigma(a^\mathrm{class}),
\end{split}
\end{equation*}
where $a^\mathrm{feat}$ is the $M \times 1$ vector of pre-activations for the feature extraction layer, $h^\mathrm{feat}$ denotes the $M \times 1$ output of the feature extraction layer, $a^\mathrm{class}$ is the scalar pre-activation of the classification layer, and $p(\mathrm{t}_i = 1 | x_i, \theta)$ is the output of the neural network, where $\sigma(\cdot)$ denotes the sigmoid function defined at the beginning of part I.
Note that the activation function $h(\cdot)$ is applied element-wise to the vector $a^\mathrm{feat}$ in the equations above.


## Question 7 [15 points in total]

In the following questions, we will implement the forward pass of the neural network step by step.

#### Question 7.1 [5 points]

Complete the function `nn_pre_activation` which takes the input $h$ and the weights $W$ of any of the two defined layers, i.e. $(h, W) \in \{(x_i, W^\mathrm{feat}), (h^\mathrm{feat}, W^\mathrm{class})\}$, and returns the corresponding pre-activation vector $a = W h$, where $a = a^\mathrm{feat}$ if $(h, W) = (x_i, W^\mathrm{feat})$, and $a = a^\mathrm{class}$ if $(h, W) = (h^\mathrm{feat}, W^\mathrm{class})$.

In [18]:
def nn_pre_activation(input_layer, layer_weights):
    """
    Parameters
    ----------
    input_layer : np.ndarray
        L_in x 1 vector representing the layer input (L_in in {K, M})
    
    layer_weights : np.ndarray
        L_out x L_in matrix representing the layer weights ((L_in, L_out) in {(K, M), (M, 1)})
    
    Returns
    -------
    pre_activation : np.ndarray
        L_out x 1 vector of pre-activations
    """

    # Write your code here

    # We can use matrix multiplication to find the pre-activation vector
    pre_activation = layer_weights @ input_layer
    
    return pre_activation

In [19]:
dummy_input = np.array([0.233, 0.275, 0.239, 0.258, 0.4, 0., 0.]).reshape(-1, 1)
dummy_weights = np.array([
    [-0.52, -0.05,  0.47, -0.37, -0.32,  0.02, -0.33],
    [ 0.29,  0.01,  0.31, -1.07, -0.07,  0.43,  0.16],
    [-0.86,  0.6 , -0.21, -0.02,  0.12,  0.04, -0.09],
    [-0.39,  0.76,  0.43,  0.17,  0.97, -0.36, -0.19],
    [-0.23, -0.37,  0.08,  0.54, -0.21,  0.11, -0.08],
    [-0.76, -0.18,  0.92,  0.54,  0.54, -0.22,  0.46],
    [ 0.05,  0.31,  0.93, -0.13, -0.02, -0.01, -1.1 ],
    [-0.35, -0.58, -0.77, -0.35, -0.37, -0.58,  0.17],
    [ 0.7 ,  0.01,  0.8 , -1.22, -1.02, -0.35, -0.15],
    [ 0.42, -0.24,  1.3 , -0.62,  0.54, -0.49,  0.08]
])
dummy_pre_activation = nn_pre_activation(dummy_input, dummy_weights)


print(f"Dummy input:\n{dummy_input}")
print(f"Dummy layer weights:\n{dummy_weights}")
print(f"Computed pre-activation vector:\n{dummy_pre_activation}")

Dummy input:
[[0.233]
 [0.275]
 [0.239]
 [0.258]
 [0.4  ]
 [0.   ]
 [0.   ]]
Dummy layer weights:
[[-0.52 -0.05  0.47 -0.37 -0.32  0.02 -0.33]
 [ 0.29  0.01  0.31 -1.07 -0.07  0.43  0.16]
 [-0.86  0.6  -0.21 -0.02  0.12  0.04 -0.09]
 [-0.39  0.76  0.43  0.17  0.97 -0.36 -0.19]
 [-0.23 -0.37  0.08  0.54 -0.21  0.11 -0.08]
 [-0.76 -0.18  0.92  0.54  0.54 -0.22  0.46]
 [ 0.05  0.31  0.93 -0.13 -0.02 -0.01 -1.1 ]
 [-0.35 -0.58 -0.77 -0.35 -0.37 -0.58  0.17]
 [ 0.7   0.01  0.8  -1.22 -1.02 -0.35 -0.15]
 [ 0.42 -0.24  1.3  -0.62  0.54 -0.49  0.08]]
Computed pre-activation vector:
[[-0.24604]
 [-0.15965]
 [-0.04273]
 [ 0.65276]
 [-0.0809 ]
 [ 0.34862]
 [ 0.27763]
 [-0.66338]
 [-0.36571]
 [ 0.3986 ]]


#### Question 7.2 [5 points]

Complete the function `nn_activation` which takes as input pre-activation vector $a^\mathrm{feat}$ and returns the output of the feature extraction layer $h^\mathrm{feat} = h(a^\mathrm{feat})$, where $h(\cdot)$ is applied element-wise to the vector $a^\mathrm{feat}$.


In [20]:
def nn_activation(pre_activation):
    """
    Parameters
    ----------
    pre_activation : np.ndarray
        M x 1 vector of pre-activations
    
    Returns
    -------
    layer_output : np.ndarray
        M x 1 vector of element-wise activations (i.e., feature layer output)
    """

    # Write your code here

    # h is ReLU, so:
    layer_output = np.maximum(pre_activation, 0)
    return layer_output


In [21]:
dummy_pre_activation = np.array([-0.806, -0.234, 1.106, 1.241, -1.79, 0.649, -0.397, -1.276, 0.149, -0.85]).reshape(-1, 1)
dummy_output_layer = nn_activation(dummy_pre_activation)


print(f"Dummy pre-activation vector:\n{dummy_pre_activation}")
print(f"Computed activation vector (output of layer):\n{dummy_output_layer}")

Dummy pre-activation vector:
[[-0.806]
 [-0.234]
 [ 1.106]
 [ 1.241]
 [-1.79 ]
 [ 0.649]
 [-0.397]
 [-1.276]
 [ 0.149]
 [-0.85 ]]
Computed activation vector (output of layer):
[[0.   ]
 [0.   ]
 [1.106]
 [1.241]
 [0.   ]
 [0.649]
 [0.   ]
 [0.   ]
 [0.149]
 [0.   ]]


#### Question 7.3 [5 points]

Complete the function `nn_forward_pass` which takes as input a covariate vector $x_i$, the layers weights $W^\mathrm{feat}$ and $W^\mathrm{class}$; and returns the neural network soft prediction $p(\mathrm{t}_i = 1 | x_i, \theta)$ for $\theta = \{W^\mathrm{feat}, W^\mathrm{class}\}$.

**Be mindful of the output shape**: in this coursework, we will assume that the neural network returns the soft-prediction $p(\mathrm{t}_i = 1 | x_i, \theta)$ as a scalar value.

In [22]:
def nn_forward_pass(nn_input, weights_feat, weights_class):
    """
    Parameters
    ----------
    nn_input : np.ndarray
        K x 1 covariate vector sample
    
    weights_feat : np.ndarray
        M x K matrix representing the weights of the feature extraction layer
    
    weights_class : np.ndarray
        1 x M matrix representing the weights of the classification layer
    
    Returns
    -------
    soft_prediction : float
        Scalar value representing the neural network soft prediction
    """

    # Write your code here

    # Using nn_pre_activation, nn_activation and stepping though system.
    
    a_feat = nn_pre_activation(nn_input, weights_feat) # Calculate vector a_feat
    
    h_feat = nn_activation(a_feat) # Apply ReLU to a_feat to get h_feat
    
    a_class = nn_pre_activation(h_feat, weights_class) # Multiply by weights to get classification layer a_class
    
    soft_prediction = sigmoid(a_class) # Apply sigmoid to produce soft predictions
    
    return soft_prediction


In [23]:
# Create a dummy covariates representing of 10 datapoints
dummy_inputs = np.array([
    [0.233, 0.275, 0.239, 0.258, 0.4  , 0.   , 0.   ],
    [0.278, 0.31 , 0.325, 0.223, 0.54 , 0.   , 0.24 ],
    [0.433, 0.37 , 0.324, 1.191, 0.985, 0.   , 0.   ],
    [0.267, 0.36 , 0.385, 0.821, 0.535, 0.082, 0.3  ],
    [0.3  , 0.41 , 0.519, 0.27 , 0.76 , 0.272, 0.39 ],
    [0.233, 0.4  , 0.536, 0.693, 0.59 , 0.   , 0.   ],
    [0.567, 0.42 , 0.449, 0.586, 0.905, 0.192, 0.21 ],
    [0.411, 0.39 , 0.345, 0.258, 0.44 , 0.   , 0.3  ],
    [0.489, 0.4  , 0.43 , 0.402, 0.66 , 0.   , 0.   ],
    [0.444, 0.39 , 0.37 , 0.439, 0.63 , 0.022, 0.27 ]
])

# Model parameters
dummy_weights_feat = np.array([
    [-0.52, -0.05,  0.47, -0.37, -0.32,  0.02, -0.33],
    [ 0.29,  0.01,  0.31, -1.07, -0.07,  0.43,  0.16],
    [-0.86,  0.6 , -0.21, -0.02,  0.12,  0.04, -0.09],
    [-0.39,  0.76,  0.43,  0.17,  0.97, -0.36, -0.19],
    [-0.23, -0.37,  0.08,  0.54, -0.21,  0.11, -0.08],
    [-0.76, -0.18,  0.92,  0.54,  0.54, -0.22,  0.46],
    [ 0.05,  0.31,  0.93, -0.13, -0.02, -0.01, -1.1 ],
    [-0.35, -0.58, -0.77, -0.35, -0.37, -0.58,  0.17],
    [ 0.7 ,  0.01,  0.8 , -1.22, -1.02, -0.35, -0.15],
    [ 0.42, -0.24,  1.3 , -0.62,  0.54, -0.49,  0.08]
])
dummy_weights_class = np.array([
    [ 1.96, 0.88, 0.1, -0.51, 1.24, -0.1, -0.31, -0.96, 0.05, 0.85]
])

# Compute forward pass for each input
dummy_outputs = []
for i in range(len(dummy_inputs)):
    input_vector = dummy_inputs[i].reshape(-1, 1)
    soft_pred = nn_forward_pass(input_vector, dummy_weights_feat, dummy_weights_class)
    dummy_outputs.append(soft_pred)
dummy_outputs = np.array(dummy_outputs).reshape(-1, 1)

print(f"Predicted probabilities of having diabetes (dummy inputs and parameters):\n{dummy_outputs}")

Predicted probabilities of having diabetes (dummy inputs and parameters):
[[0.47127544]
 [0.51334258]
 [0.4093323 ]
 [0.46703696]
 [0.53523326]
 [0.44427713]
 [0.47716762]
 [0.5264456 ]
 [0.48588795]
 [0.49776611]]


### Question 8 [25 points in total]

In the following questions, we will implement the backward pass of the neural network step by step.
The objective is to compute the derivatives of the log-loss $\ell_i(\theta) = -\log(p(\mathrm{t}_i = t_i | x_i, \theta))$ with respect to each element of $\theta = \{W^\mathrm{feat}, W^\mathrm{class}\}$ for a given datapoint $(x_i, t_i) \in \mathcal{D}$.
Accordingly, we will write the derivatives of $\ell_i(\theta)$ with respect to each weight of the matrix $W^\mathrm{feat} = [w^\mathrm{feat}_{k, m}]_{(k, m) \in \{0, ..., K-1\} \times \{0, ..., M-1\}}$ as the $M \times K$ matrix
\begin{equation*}
    \nabla_{W^\mathrm{feat}} \ell_i(\theta) = \begin{bmatrix}
        \frac{\partial \ell_i(\theta)}{\partial w^\mathrm{feat}_{0, 0}} & \dots & \frac{\partial \ell_i(\theta)}{\partial w^\mathrm{feat}_{0, K-1}} \\
        \vdots & \ddots & \vdots \\
        \frac{\partial \ell_i(\theta)}{\partial w^\mathrm{feat}_{M-1, 0}} & \dots & \frac{\partial \ell_i(\theta)}{\partial w^\mathrm{feat}_{M-1, K-1}}
    \end{bmatrix}.
\end{equation*}
Similarly, we define the $1 \times M$ row vector $\nabla_{W^\mathrm{class}} \ell_i(\theta)$ of the derivatives of $\ell_i(\theta)$ with respect to the elements of $W^\mathrm{class}$.
Note that $\ell_i(\theta)$ is sometimes (equivalently) expressed as $\ell_i(\theta) = -\log(\sigma(\mathrm{t}^{\pm}_i a^\mathrm{class}))$ in the lecture slides.

We denote as
\begin{equation*}
    \delta^\mathrm{class} = \frac{\partial \ell_i(\theta)}{\partial a^\mathrm{class}}
\end{equation*}
the scalar backpropagation error of the classification layer, and as
\begin{equation*}
    \delta^\mathrm{feat} = \left[ \frac{\partial \ell_i(\theta)}{\partial a^\mathrm{feat}_0}, ..., \frac{\partial \ell_i(\theta)}{\partial a^\mathrm{feat}_{M-1}} \right]^\top
\end{equation*}
the $M \times 1$ backpropagation error vector of the feature extraction layer, for $a^\mathrm{feat} = [a^\mathrm{feat}_0, ..., a^\mathrm{feat}_{M-1}]^\top$.
Following the backward version of the neural network computational graph, these two quantities can be related as
\begin{equation*}
    \delta^\mathrm{feat} = h'(a^\mathrm{feat}) \odot \left( (W^\mathrm{class})^\top \delta^\mathrm{class} \right),
\end{equation*}
where $h'(a^\mathrm{feat}) = {dh(a^\mathrm{feat})} / {da^\mathrm{feat}}$ is the derivative of the activation function $h(\cdot)$ evaluated element-wise at $a^\mathrm{feat}$, and $\odot$ denotes the element-wise multiplication of two vectors.

#### Question 8.1 [5 points]

Complete the function `nn_activation_derivative` which takes as input the pre-activation vector $a^\mathrm{feat}$ and outputs the ReLu derivative evaluated element-wise at $a^\mathrm{feat}$, i.e., $h'(a^\mathrm{feat}) = [h'(a^\mathrm{feat}_0), ..., h'(a^\mathrm{feat}_{M-1})]^\top$.
The derivative $h'(\cdot)$ must be computed using **symbolic differentiation** (and **not** using numerical differentiation).
Note that the derivative at $0$ is undefined, and we will assume it to be equal to $0$ in this coursework, i.e., $h'(0) = 0$.

In [24]:
def nn_activation_derivative(pre_activation):
    """
    Parameters
    ----------
    pre_activation : np.ndarray
        M x 1 vector of pre-activations
    
    Returns
    -------
    activation_derivative : np.ndarray
        M x 1 vector of activation derivatives evaluated at each element of the `pre_activation` vector
    """

    # Write your code here

    # Derivative of ReLU = 1 if a > 0, otherwise 0.
    
    activation_derivative = (pre_activation > 0).astype(int)
    return activation_derivative


In [25]:
dummy_pre_activation = np.array([-0.806, -0.234, 1.106, 1.241, -1.79 , 0.649, -0.397, -1.276, 0.149, -0.85]).reshape(-1, 1)

dummy_activation_derivative = nn_activation_derivative(dummy_pre_activation)


print(f"Dummy pre-activation vector:\n{dummy_pre_activation}")
print(f"Computed activation-derivative vector:\n{dummy_activation_derivative}")

Dummy pre-activation vector:
[[-0.806]
 [-0.234]
 [ 1.106]
 [ 1.241]
 [-1.79 ]
 [ 0.649]
 [-0.397]
 [-1.276]
 [ 0.149]
 [-0.85 ]]
Computed activation-derivative vector:
[[0]
 [0]
 [1]
 [1]
 [0]
 [1]
 [0]
 [0]
 [1]
 [0]]


#### Question 8.2 [5 points]

Complete the function `nn_backprop_error_classification_layer` which takes as input the soft prediction $p(\mathrm{t}_i = 1 | x_i, \theta)$ computed during the forward pass and the target value $t_i$; and returns the backpropagation error at the classification layer $\delta^\mathrm{class}$.

**Take a careful look at the specified output shape**: in this coursework, we will consider the backpropagation error at the classification layer $\delta^\mathrm{class}$ to be specified as a $1 \times 1$ matrix.

In [26]:
def nn_backprop_error_classification_layer(soft_prediction, target):
    """
    Parameters
    ----------
    soft_prediction : float
        Scalar value representing the neural network soft prediction
    
    target : int
        Scalar target value (`1` if the patient has diabetes, otherwise `0`)
    
    Returns
    -------
    backprop_error_class : np.ndarray
        1 x 1 matrix representing the backpropagation error at the classification layer
    """

    # Write your code here

    backprop_error_class = (soft_prediction - target) # Calculate the error
    
    return np.array(backprop_error_class).reshape(1,1) # Make the error a numpy array and then reshape to get 1 x 1 matrix
 
    


In [27]:
dummy_soft_prediction = 0.72
dummy_target = 1

dummy_backprop_error_class = nn_backprop_error_classification_layer(dummy_soft_prediction, dummy_target)


print(f"Computed backpropagation error at the classification layer (dummy inputs):\n{dummy_backprop_error_class}")

Computed backpropagation error at the classification layer (dummy inputs):
[[-0.28]]


#### Question 8.3 [5 points]

Complete the function `nn_backprop_error_feature_layer` which takes as input
- the element-wise activation derivatives $h'(a^\mathrm{feat})$,
- the weights $W^\mathrm{class}$ of the classification layer,
- the backpropagation error at the classification layer $\delta^\mathrm{class}$;

and returns the backpropagation error at the feature extraction layer $\delta^\mathrm{feat}$.


In [28]:
def nn_backprop_error_feature_layer(activation_derivative, weights_class, backprop_error_class):
    """
    Parameters
    ----------
    activation_derivative : np.ndarray
        M x 1 vector of activation derivatives
    
    weights_class : np.ndarray
        1 x M matrix representing the weights of the classification layer
    
    backprop_error_class : np.ndarray
        1 x 1 matrix representing the backpropagation error at the classification layer
    
    Returns
    -------
    backprop_error_feat : np.ndarray
        M x 1 vector representing the backpropagation error at the feature layer
    """

    # Write your code here

    backprop_error_feat = activation_derivative * (weights_class.T * backprop_error_class)

    return backprop_error_feat

In [29]:
dummy_activation_derivative = np.array([0., 0., 1., 0., 1., 1., 1., 0., 0., 1.]).reshape(-1, 1)
dummy_weights_class = np.array([
    [ 1.96, 0.88, 0.1, -0.51, 1.24, -0.1, -0.31, -0.96, 0.05, 0.85]
])
dummy_backprop_error_class = np.array([[-0.5]])

dummy_backprop_error_feat = nn_backprop_error_feature_layer(dummy_activation_derivative, dummy_weights_class, dummy_backprop_error_class)


print(f"Computed backpropagation error at the feature layer (dummy inputs and parameters):\n{dummy_backprop_error_feat}")

Computed backpropagation error at the feature layer (dummy inputs and parameters):
[[-0.   ]
 [-0.   ]
 [-0.05 ]
 [ 0.   ]
 [-0.62 ]
 [ 0.05 ]
 [ 0.155]
 [ 0.   ]
 [-0.   ]
 [-0.425]]


#### Question 8.4 [5 points]

Complete the function `nn_weights_gradient` which, for any of the two defined layers, takes its input $h \in \{x_i, h^\mathrm{feat}\}$ computed during the forward pass and its corresponding backpropagation error $\delta \in \{\delta^\mathrm{feat}, \delta^\mathrm{class}\}$ computed during the backward pass; and returns the gradient $\nabla_W l_i(\theta)$ with respect to the weights $W \in \{W^\mathrm{feat}, W^\mathrm{class}\}$ of the considered layer.

In [32]:
def nn_weights_gradient(input_layer, backprop_error_layer):
    """
    Parameters
    ----------
    input_layer : np.ndarray
        L_in x 1 vector representing the layer input (L_in in {K, M})
    
    backprop_error_layer : np.ndarray
        L_out x 1 matrix representing the backpropagation error at the layer (L_out in {M, 1})
    
    Returns
    -------
    weights_gradient : np.ndarray
        L_out x L_in matrix representing the gradient of the log-loss with respect to the weights of the layer ((L_in, L_out) in {(K, M), (M, 1)})
    """

    # Write your code here
    
    # calculate weights_gradient as matrix multiplication of input layer and backprop error
    weights_gradient = backprop_error_layer @ input_layer.T 
    return weights_gradient

In [33]:
# Gradient at classificaiton layer
dummy_input_class = np.array([0.0, 0.0, 1.106, 1.241, 0.0 , 0.649, 0.0, 0.0, 0.149, 0.0]).reshape(-1, 1)
dummy_backprop_error_class = np.array([[-0.5]])

dummy_weights_class_gradient = nn_weights_gradient(dummy_input_class, dummy_backprop_error_class)


print(f"Computed gradient for weights at classification layer (dummy inputs):\n{dummy_weights_class_gradient}")

Computed gradient for weights at classification layer (dummy inputs):
[[ 0.      0.     -0.553  -0.6205  0.     -0.3245  0.      0.     -0.0745
   0.    ]]


In [34]:
# Gradient at feature layer
dummy_input_feat = np.array([ 0.36, 0.385, 0.821, 0.535, 0.3]).reshape(-1, 1)
dummy_backprop_error_feat = np.array([0., 0.07, 0.57, 0., 0., 0., -0.26, -0.81, -0.32, 0.75]).reshape(-1, 1)

dummy_weights_feat_gradient = nn_weights_gradient(dummy_input_feat, dummy_backprop_error_feat)


print(f"Computed gradient for weights at feature layer (dummy inputs):\n{dummy_weights_feat_gradient}")

Computed gradient for weights at feature layer (dummy inputs):
[[ 0.       0.       0.       0.       0.     ]
 [ 0.0252   0.02695  0.05747  0.03745  0.021  ]
 [ 0.2052   0.21945  0.46797  0.30495  0.171  ]
 [ 0.       0.       0.       0.       0.     ]
 [ 0.       0.       0.       0.       0.     ]
 [ 0.       0.       0.       0.       0.     ]
 [-0.0936  -0.1001  -0.21346 -0.1391  -0.078  ]
 [-0.2916  -0.31185 -0.66501 -0.43335 -0.243  ]
 [-0.1152  -0.1232  -0.26272 -0.1712  -0.096  ]
 [ 0.27     0.28875  0.61575  0.40125  0.225  ]]


#### Question 8.5 [5 points]

Complete the function `nn_forward_and_backward_pass` which takes as input 
- the vector of covariates $x_i$,
- the weights $W^\mathrm{feat}$ and $W^\mathrm{class}$ of both layers,
- the target $t_i$;

and returns
- the soft prediction $p(\mathrm{t}_i = 1 | x_i, \theta)$ computed during a forward pass,
- the gradient of the log-loss with respect to the weights of the feature extraction layer $\nabla_{W^\mathrm{feat}} l_i(\theta)$,
- the gradient of the log-loss with respect to the weights of the classification layer $\nabla_{W^\mathrm{class}} l_i(\theta)$.


In [35]:
def nn_forward_and_backward_pass(nn_input, weights_feat, weights_class, target):
    """
    Parameters
    ----------
    nn_input : np.ndarray
        K x 1 covariate vector sample
    
    weights_feat : np.ndarray
        M x K matrix representing the weights of the feature extraction layer
    
    weights_class : np.ndarray
        1 x M matrix representing the weights of the classification layer
    
    target : int
        Scalar target value (`1` if the patient has diabetes, otherwise `0`)
    
    Returns
    -------
    soft_prediction : float
        Scalar value representing the neural network soft prediction
    
    weights_feat_grad : np.ndarray
        M x K matrix representing the gradient of the log-loss with respect to the weights of the feature extraction layer
    
    weights_class_grad : np.ndarray
        1 x M matrix representing the gradient of the log-loss with respect to the weights of the classification layer
    """

    # Write your code here

    # Forward Pass:

    # Matrix multiplication to calculate a_feat
    a_feat = weights_feat @ nn_input

    # Apply ReLU
    h_feat = np.maximum(a_feat, 0)

    # Calculate a_class
    a_class = np.dot(weights_class, h_feat)

    # Apply sigmoid to get soft_prediction
    soft_prediction = 1/(1+np.exp(-a_class))

    # Using back propagation to calculate gradients
    error = soft_prediction - target
    
    weights_class_grad = error*h_feat.T
    
    # Backprop through ReLU to find gradient of hidden features
    h_grad = error * weights_class.T * (h_feat > 0)

    weights_feat_grad = np.dot(h_grad, nn_input.T)

    return soft_prediction, weights_feat_grad, weights_class_grad
    
    
    




In [36]:
# Create a dummy inputs sample
dummy_input = np.array([0.233, 0.275, 0.239, 0.258, 0.4, 0., 0.]).reshape(-1, 1)
dummy_target = 1

# Model parameters
dummy_weights_feat = np.array([
    [-0.52, -0.05,  0.47, -0.37, -0.32,  0.02, -0.33],
    [ 0.29,  0.01,  0.31, -1.07, -0.07,  0.43,  0.16],
    [-0.86,  0.6 , -0.21, -0.02,  0.12,  0.04, -0.09],
    [-0.39,  0.76,  0.43,  0.17,  0.97, -0.36, -0.19],
    [-0.23, -0.37,  0.08,  0.54, -0.21,  0.11, -0.08],
    [-0.76, -0.18,  0.92,  0.54,  0.54, -0.22,  0.46],
    [ 0.05,  0.31,  0.93, -0.13, -0.02, -0.01, -1.1 ],
    [-0.35, -0.58, -0.77, -0.35, -0.37, -0.58,  0.17],
    [ 0.7 ,  0.01,  0.8 , -1.22, -1.02, -0.35, -0.15],
    [ 0.42, -0.24,  1.3 , -0.62,  0.54, -0.49,  0.08]
])
dummy_weights_class = np.array([
    [ 1.96, 0.88, 0.1, -0.51, 1.24, -0.1, -0.31, -0.96, 0.05, 0.85]
])

# Compute forward pass for each input
dummy_soft_pred, dummy_weights_feat_grad, dummy_weights_class_grad = nn_forward_and_backward_pass(
    dummy_input,
    dummy_weights_feat,
    dummy_weights_class,
    dummy_target
)

print(f"Dummy input:\n{dummy_input}")
print(f"Dummy target:\n{dummy_target}")
print(f"Predicted probability of having diabetes (dummy parameters):\n{dummy_soft_pred}")
print(f"Gradient of the weights at the feature extraction layer (dummy parameters):\n{dummy_weights_feat_grad}")
print(f"Gradient of the weights at the classification layer (dummy parameters):\n{dummy_weights_class_grad}")

Dummy input:
[[0.233]
 [0.275]
 [0.239]
 [0.258]
 [0.4  ]
 [0.   ]
 [0.   ]]
Dummy target:
1
Predicted probability of having diabetes (dummy parameters):
[[0.47127544]]
Gradient of the weights at the feature extraction layer (dummy parameters):
[[-0.         -0.         -0.         -0.         -0.         -0.
  -0.        ]
 [-0.         -0.         -0.         -0.         -0.         -0.
  -0.        ]
 [-0.         -0.         -0.         -0.         -0.         -0.
  -0.        ]
 [ 0.06282834  0.07415362  0.06444624  0.06956958  0.10785981  0.
   0.        ]
 [-0.         -0.         -0.         -0.         -0.         -0.
  -0.        ]
 [ 0.01231928  0.01453993  0.01263652  0.01364109  0.02114898  0.
   0.        ]
 [ 0.03818978  0.04507377  0.0391732   0.04228739  0.06556185  0.
   0.        ]
 [ 0.          0.          0.          0.          0.          0.
   0.        ]
 [-0.         -0.         -0.         -0.         -0.         -0.
  -0.        ]
 [-0.1047139  -0.12358937 

### Question 9 [10 points total]

#### Question 9.1 [5 points]

Complete the function `train_neural_network` which takes as input
- the data matrix $X_\mathcal{D}$,
- its associated target vector $t_\mathcal{D}$,
- an initial value $W^{\mathrm{feat}, (0, 0)}$ of the weights at the feature extraction layer,
- an initial value $W^{\mathrm{class}, (0, 0)}$ of the weights at the classification layer,
- a learning rate $\gamma > 0$
- a number of _epochs_ $J \geq 1$;

and returns the learned weights $W^{\mathrm{feat}, (J-1, N)}$ and $W^{\mathrm{class}, (J-1, N)}$ after $J \cdot N$ gradient-descent steps over $J$ epochs.

Each epoch corresponds to a pass over the dataset $\mathcal{D}$ using a (**non-random**) consecutive sequence minibatches $\{(x_i, t_i)\}$ of size $1$ for each gradient update.
More specifically, the $i$-th gradient update at the $j$-th epoch is given as
\begin{equation*}
    \begin{cases}
    W^{\mathrm{feat}, (j, i+1)} = W^{\mathrm{feat}, (j, i)} - \gamma \nabla_{W^\mathrm{feat}} l_i(\theta^{(j, i)}) \\
    W^{\mathrm{class}, (j, i+1)} = W^{\mathrm{class}, (j, i)} - \gamma \nabla_{W^\mathrm{class}} l_i(\theta^{(j, i)})
    \end{cases}
\end{equation*}
for $i \in \{0, ..., N-1\}$, $j \in \{0, ..., J-1\}$, and $\theta^{(j, i)} = \{W^{\mathrm{feat}, (j, i)}, W^{\mathrm{class}, (j, i)}\}$.
The last value of the current epoch becomes the initial value of the next epoch, that is $\theta^{(j, N)} = \theta^{(j+1, 0)}$ for $j \in \{0, ..., J-2\}$.


In [37]:
def train_neural_network(inputs, targets, init_weights_feat, init_weights_class, lr, n_epochs):
    """
    Parameters
    ----------
    inputs : np.ndarray
        N x K data matrix
    
    targets : np.ndarray
        N x 1 target vector
        
    init_weights_feat : np.ndarray
        M x K matrix representing the initial weights of the feature extraction layer
        
    init_weights_feat : np.ndarray
        1 x M matrix representing the initial weights of the classification layer
    
    lr : float
        Scalar learning rate
    
    n_epochs : int
        Number of epochs
    
    Returns
    -------
    learned_weights_feat : np.ndarray
        M x K matrix representing the learned weights of the feature extraction layer after `N * n_epochs` gradient-descent steps
    
    learned_weights_class : np.ndarray
        1 x M matrix representing the learned weights of the classification layer after `N * n_epochs` gradient-descent steps
    """

    # Write your code here

    weights_feat = init_weights_feat
    weights_class = init_weights_class

    for i in range(n_epochs): 
        for idx in range(len(targets)):
            target = targets[idx] # Get target
            nn_input = inputs[idx,:].reshape(-1,1) # Get corrosponding inputs
            
            # Use function nn_forward_and_backward_pass to compute soft_prediction, weights_feat_grad and weights_class_grad
            soft_prediction, weights_feat_grad, weights_class_grad = nn_forward_and_backward_pass(nn_input, weights_feat, weights_class, target)
            
            # Update weights_feat and weights_class
            weights_feat = weights_feat - lr*weights_feat_grad
            weights_class = weights_class - lr*weights_class_grad

    # We don't need to use np.copy() because we are not going to modify further
    learned_weights_feat = weights_feat 
    learned_weights_class = weights_class

    return learned_weights_feat, learned_weights_class
        

In [38]:
# Create a dummy dataset representing of 10 datapoints
dummy_inputs = np.array([
    [0.233, 0.275, 0.239, 0.258, 0.4  , 0.   , 0.   ],
    [0.278, 0.31 , 0.325, 0.223, 0.54 , 0.   , 0.24 ],
    [0.433, 0.37 , 0.324, 1.191, 0.985, 0.   , 0.   ],
    [0.267, 0.36 , 0.385, 0.821, 0.535, 0.082, 0.3  ],
    [0.3  , 0.41 , 0.519, 0.27 , 0.76 , 0.272, 0.39 ],
    [0.233, 0.4  , 0.536, 0.693, 0.59 , 0.   , 0.   ],
    [0.567, 0.42 , 0.449, 0.586, 0.905, 0.192, 0.21 ],
    [0.411, 0.39 , 0.345, 0.258, 0.44 , 0.   , 0.3  ],
    [0.489, 0.4  , 0.43 , 0.402, 0.66 , 0.   , 0.   ],
    [0.444, 0.39 , 0.37 , 0.439, 0.63 , 0.022, 0.27 ]
])
dummy_targets = np.array([1, 0, 0, 1, 0, 1, 1, 1, 0, 0], dtype=float).reshape(-1, 1)

# Init model parameters
dummy_init_weights_feat = np.array([
    [ 0.47,  0.13, -0.49,  0.25,  0.06, -0.08, -0.09],
    [ 0.05,  0.03, -0.56,  0.13,  0.11,  0.33, -0.57],
    [ 0.53, -0.4 , -0.32,  0.11, -0.51,  0.33, -0.44],
    [-0.19,  0.18,  0.45, -0.58,  0.03,  0.31, -0.55],
    [-0.33,  0.54, -0.2 ,  0.56,  0.07, -0.56,  0.53],
    [ 0.37,  0.4 ,  0.03,  0.05,  0.4 ,  0.44,  0.58],
    [ 0.5 ,  0.41, -0.18, -0.01,  0.19,  0.39, -0.32],
    [-0.39,  0.07,  0.08, -0.57, -0.2 , -0.35, -0.43],
    [-0.16, -0.05, -0.49, -0.51,  0.57,  0.35, -0.43],
    [ 0.58, -0.48, -0.33, -0.43, -0.36, -0.11, -0.44]
])
dummy_init_weights_class = np.array([
    [-0.2 ,  0.29,  0.55,  0.17,  0.3 , -0.19,  0.38,  0.69,  0.46, -0.52]
])

# Training parameters
dummy_n_epochs = 1000
dummy_lr = 0.1


# Train neural network using dummy dataset
dummy_learned_weights_feat, dummy_learned_weights_class = train_neural_network(
    dummy_inputs,
    dummy_targets,
    dummy_init_weights_feat,
    dummy_init_weights_class,
    dummy_lr,
    dummy_n_epochs
)


print(f"Learned weights at the feature extraction layer (dummy dataset):\n{dummy_learned_weights_feat}")
print(f"Learned weights at the classification layer (dummy dataset):\n{dummy_learned_weights_class}")

Learned weights at the feature extraction layer (dummy dataset):
[[ 6.56076243 -5.11561887 -0.78382091  1.81270011 -1.00434546 -5.4941999
  -1.10922616]
 [ 0.03045942  0.0133025  -0.57462159  0.07625212  0.06554856  0.33
  -0.57      ]
 [ 0.53       -0.4        -0.32        0.11       -0.51        0.33
  -0.44      ]
 [-0.19        0.18        0.45       -0.58        0.03        0.31
  -0.55      ]
 [-0.40187122  4.40830225  3.65632565 -0.1158413  -5.53613456 -1.1439153
   2.4539135 ]
 [-2.43100814  0.40944219  0.99017986 -2.23846213  1.98877758 -2.45975853
   3.83793263]
 [-0.36244435  2.500576   -0.84207685  1.71983894 -0.06408059  2.24890808
  -1.53569447]
 [-0.39        0.07        0.08       -0.57       -0.2        -0.35
  -0.43      ]
 [-0.16       -0.05       -0.49       -0.51        0.57        0.35
  -0.43      ]
 [ 0.58       -0.48       -0.33       -0.43       -0.36       -0.11
  -0.44      ]]
Learned weights at the classification layer (dummy dataset):
[[-8.75188735  0.2786

#### Question 9.2 [5 points]

Complete the function `train_and_test_neural_network` which takes as input
- the training data matrix $X_{\mathcal{D}^\mathrm{tr}}$,
- the training target vector $t_{\mathcal{D}^\mathrm{tr}}$,
- the test data matrix $X_{\mathcal{D}^\mathrm{te}}$,
- the test target vector $t_{\mathcal{D}^\mathrm{te}}$,
- an initial value $W^{\mathrm{feat}, (0, 0)}$ of the weights at the feature extraction layer,
- an initial value $W^{\mathrm{class}, (0, 0)}$ of the weights at the classification layer,
- a learning rate $\gamma > 0$
- a number of epochs $J \geq 1$;

and returns
- the learned weights $W^{\mathrm{feat}, (J-1, N^\mathrm{tr})}$ and $W^{\mathrm{class}, (J-1, N^\mathrm{tr})}$ after $J \cdot N^\mathrm{tr}$ gradient-descent steps over $J$ epochs,
- the training loss $\mathcal{L}_{\mathcal{D}^\mathrm{tr}}(\theta^{(J-1, N^\mathrm{tr})})$,
- and the test loss $\mathcal{L}_{\mathcal{D}^\mathrm{te}}(\theta^{(J-1, N^\mathrm{tr})})$.

In [39]:
def train_and_test_neural_network(inputs_tr, targets_tr, inputs_te, targets_te, init_weights_feat, init_weights_class, lr, n_epochs):
    """
    Parameters
    ----------
    inputs_tr : np.ndarray
        N_tr x K training data matrix
    
    targets_tr : np.ndarray
        N_tr x 1 training target vector

    inputs_te : np.ndarray
        N_te x K test data matrix
    
    targets_te : np.ndarray
        N_te x 1 test target vector
        
    init_weights_feat : np.ndarray
        M x K matrix representing the initial weights of the feature extraction layer
        
    init_weights_class : np.ndarray
        1 x M matrix representing the initial weights of the classification layer
    
    lr : float
        Scalar learning rate
    
    n_epochs : int
        Number of epochs
    
    Returns
    -------
    learned_weights_feat : np.ndarray
        M x K matrix representing the learned weights of the feature extraction layer after `N * n_epochs` gradient-descent steps
    
    learned_weights_class : np.ndarray
        1 x M matrix representing the learned weights of the classification layer after `N * n_epochs` gradient-descent steps

    loss_tr : float
        Scalar cross-entropy training loss

    loss_te : float
        Scalar cross-entropy test loss
    """

    # Write your code here

    # Use previous function to train the neural network:
    
    learned_weights_feat, learned_weights_class = train_neural_network(inputs_tr, targets_tr, init_weights_feat, init_weights_class, lr, n_epochs)
    
    # calculate soft predictions:
    
    a_feat_mat_te = learned_weights_feat @ inputs_te.T # Produces a matrix M x N_te, where each column represents the a_feat of a datapoint 
    
    # Apply ReLU
    h_feat_mat_te = np.maximum(a_feat_mat_te, 0) 

    # Calculate a_class
    a_class_te = learned_weights_class @ h_feat_mat_te

    # Apply sigmoid to get soft predictions
    soft_predictions_te = 1 / (1 + np.exp(-a_class_te))

    targets_te = targets_te.flatten() # reduces broadcasting issues
    
    # Calculate log-loss, using 
    loss_te = -np.mean(targets_te * np.log(soft_predictions_te) + (1 - targets_te) * np.log(1 - soft_predictions_te))
    # And again for training data
    
    # calculate soft predictions:
    
    a_feat_mat_tr = learned_weights_feat @ inputs_tr.T # Produces a matrix M x N_te, where each column represents the a_feat of a datapoint 
    
    # Apply ReLU
    h_feat_mat_tr = np.maximum(a_feat_mat_tr, 0) 

    # Calculate a_class
    a_class_tr = learned_weights_class @ h_feat_mat_tr

    # Apply sigmoid to get soft predictions
    soft_predictions_tr = 1 / (1 + np.exp(-a_class_tr))

    targets_tr = targets_tr.flatten() # reduces broadcasting issues
    
    # Calculate log-loss
    loss_tr = -np.mean(targets_tr * np.log(soft_predictions_tr) + (1 - targets_tr) * np.log(1 - soft_predictions_tr))


    
    return learned_weights_feat, learned_weights_class, loss_tr, loss_te

    

    

In [40]:
# Init model parameters
dataset_init_weights_feat = np.array([
    [ 0.47,  0.13, -0.49,  0.25,  0.06, -0.08, -0.09],
    [ 0.05,  0.03, -0.56,  0.13,  0.11,  0.33, -0.57],
    [ 0.53, -0.4 , -0.32,  0.11, -0.51,  0.33, -0.44],
    [-0.19,  0.18,  0.45, -0.58,  0.03,  0.31, -0.55],
    [-0.33,  0.54, -0.2 ,  0.56,  0.07, -0.56,  0.53],
    [ 0.37,  0.4 ,  0.03,  0.05,  0.4 ,  0.44,  0.58],
    [ 0.5 ,  0.41, -0.18, -0.01,  0.19,  0.39, -0.32],
    [-0.39,  0.07,  0.08, -0.57, -0.2 , -0.35, -0.43],
    [-0.16, -0.05, -0.49, -0.51,  0.57,  0.35, -0.43],
    [ 0.58, -0.48, -0.33, -0.43, -0.36, -0.11, -0.44]
])
dataset_init_weights_class = np.array([
    [-0.2 ,  0.29,  0.55,  0.17,  0.3 , -0.19,  0.38,  0.69,  0.46, -0.52]
])

# Training parameters
dataset_n_epochs = 50
dataset_lr = 0.05


# Train neural network and estimate the population loss for the learned weights
dataset_learned_weights_feat, dataset_learned_weights_class, dataset_nn_loss_tr, dataset_nn_loss_te = train_and_test_neural_network(
    np.copy(dataset_inputs_tr),
    np.copy(dataset_targets_tr),
    np.copy(dataset_inputs_te),
    np.copy(dataset_targets_te),
    dataset_init_weights_feat,
    dataset_init_weights_class,
    dataset_lr,
    dataset_n_epochs
)


print(f"Learned weights at the feature extraction layer (diabetes dataset):\n{dataset_learned_weights_feat}")
print(f"Learned weights at the classification layer (diabetes dataset):\n{dataset_learned_weights_class}")
print(f"Train loss (diabetes dataset): {dataset_nn_loss_tr}")
print(f"Estimated population loss for learned weights (diabetes dataset): {dataset_nn_loss_te}")

Learned weights at the feature extraction layer (diabetes dataset):
[[ 5.52106952e-01  1.07849692e+00 -1.27324764e+00 -2.91121730e-03
  -2.81108249e-01 -5.01513908e-01 -5.57851746e-01]
 [ 2.76937262e-01  2.85540122e-01 -5.87688074e-01 -9.60109208e-02
  -1.68971554e-01  6.57901532e-01 -4.78032165e-01]
 [ 5.06484828e-01 -4.13989679e-01 -3.29184281e-01  1.01355971e-01
  -5.18132212e-01  3.30000000e-01 -4.40000000e-01]
 [-5.92020733e-01 -1.27989888e-01  6.97913719e-01 -3.59479901e-01
   2.26461408e-01 -3.13281607e-01 -1.15085551e+00]
 [-1.02548424e+00  1.87189610e+00 -1.25581259e+00  9.86736115e-01
  -5.78861276e-01  2.95570096e-01 -9.30926321e-01]
 [-2.53860921e+00  4.38748570e+00  8.48110186e-02 -3.88082713e-01
  -1.77079470e+00  2.98590706e-01  3.03595976e-01]
 [ 7.30175759e-01 -3.52060525e-01 -5.15468970e-01 -5.49321435e-02
   2.97705374e-01  7.08812032e-01  2.50833608e-01]
 [-3.90000000e-01  7.00000000e-02  8.00000000e-02 -5.70000000e-01
  -2.00000000e-01 -3.50000000e-01 -4.30000000e-